### ISSUE TITLE
Images of failed cases

### ISSUE THREAD

**Issue by chengsoonong** [radiogalaxyzoo/atlas-xid#3]

**Comment by chengsoonong** [comment]
All predictors think a different IR host is the correct one

**Comment by chengsoonong** [comment]
Show all images, sort by the number of predicted hosts.

**Comment by MatthewJA** [comment]
Done this but I'll check with Julie before I put them online because they show the RGZ hosts. Also, I followed up on Heinz's question about the Norris+06 cross-identifications that looked a bit off. I thought maybe my matching (prerelease SWIRE -> public SWIRE) was failing, so I just plotted the objects directly. But everything lined up fine.

**Comment by MatthewJA** [comment]
![image](https://user-images.githubusercontent.com/2681312/32354188-b394433a-c07c-11e7-8fbd-b522e2ba75d6.png)
Here's the most-disagreed example!
